name: Deploy to GitHub Pages

# Trigger the workflow on push to the main branch or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub UI

# Permissions required for deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Match your local Node version if different
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the app
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          publish_dir: ./dist # Vite's default build output directory
          publish_branch: gh-pages # Deploy to this branch